/*
 * sensor_telemetry.h
 *
 *  Created on: 1 Jan 2026
 *      Author: Chris Thompson, VE2TCP
 */

#ifndef SENSOR_TELEMETRY_H_
#define SENSOR_TELEMETRY_H_

/**
 * This structure is generated by the python gen_header.py script from a csv file.  Change the layout in that tool
 * and re-generate this structure
 */

typedef struct __attribute__((__packed__)) {
    unsigned int timestamp : 32;
    unsigned int LPS22_pressure : 32;
    unsigned int LPS22_temp : 16;
    unsigned int SHTC3_temp : 16;
    unsigned int SHTC3_humidity : 16;
    unsigned int light_level : 8;
    unsigned int Pad1 : 8;
    unsigned int light_RGB : 32;
    unsigned int TempHumidityValid : 2;
    unsigned int PressureValid : 2;
    unsigned int ColorValid : 2;
    unsigned int Pad2 : 2;
} sensor_telemetry_t;


#endif /* SENSOR_TELEMETRY_H_ */
